// SPDX-License-Identifier: GPL-2.0-or-later
//! The plan file: a human-readable record of what `pack` will do.
//!
//! Plans are text on purpose. A plan authorises rewriting a multi-gigabyte
//! model file, and a reviewer should be able to read exactly which tensors move
//! and how before that happens.

use std::fmt::Write as _;
use std::path::Path;

/// One layer's permutation and the tensors it applies to.
#[derive(Debug, Clone)]
pub struct LayerPlan {
    /// Block index.
    pub block: u32,
    /// Every tensor carrying this layer's expert axis. All are permuted together.
    pub tensors: Vec<String>,
    /// `perm[slot] == old_expert`.
    pub perm: Vec<u32>,
    /// Predicted speedup in read time for this layer.
    pub predicted_speedup: f64,
    /// Requests per token before and after.
    pub requests_before: f64,
    /// Requests per token after.
    pub requests_after: f64,
}

/// A complete repack plan.
#[derive(Debug, Clone)]
pub struct Plan {
    /// Model the plan was computed against.
    pub model: String,
    /// Trace the plan was computed from.
    pub trace: String,
    /// Per-layer entries.
    pub layers: Vec<LayerPlan>,
}

impl Plan {
    /// Render to text.
    pub fn to_text(&self) -> String {
        let mut s = String::new();
        let _ = writeln!(s, "pmxplan 1");
        let _ = writeln!(
            s,
            "# Generated by potatomaxx. Permuting an expert axis is a relabelling:"
        );
        let _ = writeln!(
            s,
            "# every tensor listed for a layer is permuted identically, including the"
        );
        let _ = writeln!(
            s,
            "# router, so the model computes the same function bit for bit."
        );
        let _ = writeln!(s, "model {}", self.model);
        let _ = writeln!(s, "trace {}", self.trace);
        for l in &self.layers {
            let _ = writeln!(s);
            let _ = writeln!(
                s,
                "layer {} experts {} speedup {:.4} requests {:.2} -> {:.2}",
                l.block,
                l.perm.len(),
                l.predicted_speedup,
                l.requests_before,
                l.requests_after
            );
            let _ = writeln!(s, "tensors {}", l.tensors.join(","));
            let perm: Vec<String> = l.perm.iter().map(|v| v.to_string()).collect();
            let _ = writeln!(s, "perm {}", perm.join(","));
        }
        s
    }

    /// Write to `path`.
    pub fn write(&self, path: impl AsRef<Path>) -> std::io::Result<()> {
        std::fs::write(path, self.to_text())
    }

    /// Parse a plan file, rejecting anything malformed.
    pub fn parse(text: &str) -> Result<Plan, String> {
        let mut lines = text.lines().enumerate();
        let (_, first) = lines.next().ok_or("plan file is empty")?;
        if first.trim() != "pmxplan 1" {
            return Err(format!("unrecognised plan header {:?}", first.trim()));
        }
        let mut plan = Plan {
            model: String::new(),
            trace: String::new(),
            layers: Vec::new(),
        };
        let mut cur: Option<LayerPlan> = None;

        for (i, raw) in lines {
            let line = raw.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let (key, rest) = line.split_once(' ').unwrap_or((line, ""));
            match key {
                "model" => plan.model = rest.trim().to_string(),
                "trace" => plan.trace = rest.trim().to_string(),
                "layer" => {
                    if let Some(c) = cur.take() {
                        plan.layers.push(c);
                    }
                    let block: u32 = rest
                        .split_whitespace()
                        .next()
                        .and_then(|v| v.parse().ok())
                        .ok_or_else(|| format!("line {}: layer needs a block index", i + 1))?;
                    let field = |name: &str| -> Option<f64> {
                        let mut it = rest.split_whitespace();
                        while let Some(t) = it.next() {
                            if t == name {
                                return it.next().and_then(|v| v.parse().ok());
                            }
                        }
                        None
                    };
                    cur = Some(LayerPlan {
                        block,
                        tensors: Vec::new(),
                        perm: Vec::new(),
                        predicted_speedup: field("speedup").unwrap_or(1.0),
                        requests_before: field("requests").unwrap_or(0.0),
                        requests_after: 0.0,
                    });
                }
                "tensors" => {
                    let c = cur
                        .as_mut()
                        .ok_or_else(|| format!("line {}: tensors before any layer", i + 1))?;
                    c.tensors = rest
                        .split(',')
                        .map(|s| s.trim().to_string())
                        .filter(|s| !s.is_empty())
                        .collect();
                }
                "perm" => {
                    let c = cur
                        .as_mut()
                        .ok_or_else(|| format!("line {}: perm before any layer", i + 1))?;
                    let mut v = Vec::new();
                    for tok in rest.split(',') {
                        let tok = tok.trim();
                        if tok.is_empty() {
                            continue;
                        }
                        v.push(tok.parse::<u32>().map_err(|_| {
                            format!("line {}: {tok:?} is not an expert index", i + 1)
                        })?);
                    }
                    c.perm = v;
                }
                other => return Err(format!("line {}: unknown key {other:?}", i + 1)),
            }
        }
        if let Some(c) = cur {
            plan.layers.push(c);
        }
        for l in &plan.layers {
            if l.tensors.is_empty() {
                return Err(format!("layer {} lists no tensors", l.block));
            }
            if l.perm.is_empty() {
                return Err(format!("layer {} has no permutation", l.block));
            }
            let mut seen = vec![false; l.perm.len()];
            for &e in &l.perm {
                let e = e as usize;
                if e >= seen.len() || seen[e] {
                    return Err(format!(
                        "layer {} permutation is not a permutation of 0..{}",
                        l.block,
                        l.perm.len()
                    ));
                }
                seen[e] = true;
            }
        }
        Ok(plan)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> Plan {
        Plan {
            model: "m.gguf".into(),
            trace: "t.pmxtrace".into(),
            layers: vec![LayerPlan {
                block: 3,
                tensors: vec![
                    "blk.3.ffn_up_exps.weight".into(),
                    "blk.3.ffn_gate_inp.weight".into(),
                ],
                perm: vec![2, 0, 3, 1],
                predicted_speedup: 1.42,
                requests_before: 12.0,
                requests_after: 6.0,
            }],
        }
    }

    #[test]
    fn round_trips() {
        let p = sample();
        let back = Plan::parse(&p.to_text()).expect("parses");
        assert_eq!(back.model, "m.gguf");
        assert_eq!(back.layers.len(), 1);
        assert_eq!(back.layers[0].perm, vec![2, 0, 3, 1]);
        assert_eq!(back.layers[0].tensors.len(), 2);
        assert!((back.layers[0].predicted_speedup - 1.42).abs() < 1e-6);
    }

    #[test]
    fn rejects_a_bad_header() {
        assert!(Plan::parse("nope 1\n").is_err());
    }

    #[test]
    fn rejects_a_non_permutation() {
        let t = "pmxplan 1\nmodel m\ntrace t\nlayer 0\ntensors a\nperm 0,0,2\n";
        assert!(Plan::parse(t).is_err());
    }

    #[test]
    fn rejects_perm_without_a_layer() {
        assert!(Plan::parse("pmxplan 1\nperm 0,1\n").is_err());
    }

    #[test]
    fn rejects_unknown_keys() {
        assert!(Plan::parse("pmxplan 1\nfrobnicate yes\n").is_err());
    }
}
