# SPDX-License-Identifier: GPL-2.0-or-later
[package]
name = "pmx-cli"
description = "The potatomaxx command line tool."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "potatomaxx"
path = "src/main.rs"

[dependencies]
pmx-gguf = { path = "../pmx-gguf" }
pmx-probe = { path = "../pmx-probe" }
pmx-trace = { path = "../pmx-trace" }
pmx-partition = { path = "../pmx-partition" }
pmx-plan = { path = "../pmx-plan" }
pmx-cache = { path = "../pmx-cache" }
pmx-kernels = { path = "../pmx-kernels" }
pmx-kio = { path = "../pmx-kio" }
pmx-predict = { path = "../pmx-predict" }
pmx-runtime = { path = "../pmx-runtime" }
pmx-store = { path = "../pmx-store" }

[lints]
workspace = true
